### ISSUE TITLE
Possible to use without python?

### ISSUE THREAD

**Issue by majimboo** [hjweide/pyastar#17]
I was wondering how to call this from a C++ app? How to clean it up to remove all python related stuff?

Thank you!

**Comment by hjweide** [comment]
You could fork the repo and keep only the core implementation from here https://github.com/hjweide/pyastar/blob/master/src/cpp/astar.cpp#L61
to here
https://github.com/hjweide/pyastar/blob/master/src/cpp/astar.cpp#L125

You'd obviously have to rewrite the parts that pass in the data and reconstruct the path at the end, because right now they're basically meant to do data marshalling from Python to / from C++.

**Comment by hjweide** [comment]
Closing, feel free to re-open if you have more questions.
